import get_extra_fields
from datetime import date


def test_transform_person_for_redshift():
    input = {
        "vanId": 101572625,
        "dateOfBirth": "1990-08-02T00:00:00Z",
        "selfReportedRaces": [
            {"reportedRaceId": 3, "reportedRaceName": "Caucasian or White"}
        ],
        "selfReportedGenders": [
            {"reportedGenderId": 54, "reportedGenderName": "Cisgender Man"},
            {"reportedGenderId": 8, "reportedGenderName": "Male"},
            {"reportedGenderId": 10, "reportedGenderName": "Man"},
        ],
        "customFields": [
            {
                "customField": {
                    "customFieldId": 19,
                    "customFieldParentId": None,
                    "customFieldName": "Class/Economic Background",
                    "customFieldGroupId": 3,
                    "customFieldGroupName": "Misc. Information",
                    "customFieldGroupType": "Contacts",
                    "customFieldTypeId": "S",
                    "isEditable": True,
                    "maxTextboxCharacters": None,
                    "availableValues": [
                        {"id": 1, "name": "Middle-class", "parentValueId": None},
                        {
                            "id": 2,
                            "name": "Poor and working-poor",
                            "parentValueId": None,
                        },
                        {
                            "id": 3,
                            "name": "Professional/managerial-class",
                            "parentValueId": None,
                        },
                        {"id": 4, "name": "Upper/owning-class", "parentValueId": None},
                        {"id": 5, "name": "Working-class", "parentValueId": None},
                    ],
                    "isExportable": True,
                },
                "customFieldId": 19,
                "customFieldGroupId": 3,
                "assignedValue": "4",
            },
            {
                "customField": {
                    "customFieldId": 12,
                    "customFieldParentId": None,
                    "customFieldName": "Hub Affiliation",
                    "customFieldGroupId": 4,
                    "customFieldGroupName": "Hub Role Information",
                    "customFieldGroupType": "Contacts",
                    "customFieldTypeId": "S",
                    "isEditable": True,
                    "maxTextboxCharacters": None,
                    "availableValues": [
                        {
                            "id": 464,
                            "name": "Academic Magnet HS",
                            "parentValueId": None,
                        },
                        {"id": 1, "name": "Acton", "parentValueId": None},
                        {"id": 2, "name": "Adirondacks", "parentValueId": None},
                        {"id": 3, "name": "Albany", "parentValueId": None},
                        {"id": 4, "name": "Albuquerque", "parentValueId": None},
                        {"id": 378, "name": "Aliso Niguel HS", "parentValueId": None},
                        {"id": 575, "name": "Alpharetta", "parentValueId": None},
                        {"id": 5, "name": "American University", "parentValueId": None},
                        {"id": 6, "name": "Ames", "parentValueId": None},
                        {"id": 7, "name": "Amherst", "parentValueId": None},
                        {"id": 423, "name": "Amherst College", "parentValueId": None},
                        {
                            "id": 8,
                            "name": "Anacortes High School",
                            "parentValueId": None,
                        },
                        {"id": 399, "name": "Anaheim", "parentValueId": None},
                        {"id": 9, "name": "Anchorage", "parentValueId": None},
                        {"id": 424, "name": "Andover", "parentValueId": None},
                        {"id": 10, "name": "Ann Arbor", "parentValueId": None},
                        {"id": 307, "name": "Appleton", "parentValueId": None},
                        {
                            "id": 11,
                            "name": "Arcadia High School",
                            "parentValueId": None,
                        },
                        {
                            "id": 445,
                            "name": "Arizona State University",
                            "parentValueId": None,
                        },
                        {"id": 12, "name": "Arlington MA", "parentValueId": None},
                        {"id": 13, "name": "Arlington VA", "parentValueId": None},
                        {"id": 14, "name": "Asheville", "parentValueId": None},
                        {"id": 569, "name": "Ashland", "parentValueId": None},
                        {"id": 15, "name": "Atlanta", "parentValueId": None},
                        {
                            "id": 16,
                            "name": "Atlanta University Center",
                            "parentValueId": None,
                        },
                        {"id": 17, "name": "Austin", "parentValueId": None},
                        {"id": 346, "name": "Ballantyne", "parentValueId": None},
                        {"id": 379, "name": "Ballard", "parentValueId": None},
                        {"id": 18, "name": "Baltimore", "parentValueId": None},
                        {"id": 335, "name": "Bard College", "parentValueId": None},
                        {"id": 400, "name": "Basking Ridge", "parentValueId": None},
                        {"id": 19, "name": "Bates College", "parentValueId": None},
                        {"id": 360, "name": "Baton Rouge", "parentValueId": None},
                        {"id": 20, "name": "Bay Area", "parentValueId": None},
                        {"id": 21, "name": "Bear River", "parentValueId": None},
                        {"id": 22, "name": "Beaver County", "parentValueId": None},
                        {"id": 23, "name": "Beaverton", "parentValueId": None},
                        {"id": 24, "name": "Bellingham", "parentValueId": None},
                        {"id": 425, "name": "Bergen County", "parentValueId": None},
                        {"id": 25, "name": "Berkeley", "parentValueId": None},
                        {"id": 470, "name": "Berkeley High", "parentValueId": None},
                        {"id": 26, "name": "Berks", "parentValueId": None},
                        {"id": 361, "name": "Berkshire County", "parentValueId": None},
                        {"id": 362, "name": "Berwyn", "parentValueId": None},
                        {"id": 27, "name": "Bethesda", "parentValueId": None},
                        {"id": 308, "name": "Bethlehem", "parentValueId": None},
                        {"id": 570, "name": "Big Island", "parentValueId": None},
                        {"id": 28, "name": "Billings", "parentValueId": None},
                        {"id": 29, "name": "Birmingham", "parentValueId": None},
                        {"id": 446, "name": "Blackstone Valley", "parentValueId": None},
                        {"id": 30, "name": "Bloomington", "parentValueId": None},
                        {"id": 31, "name": "Blue Hills", "parentValueId": None},
                        {"id": 32, "name": "Boise", "parentValueId": None},
                        {"id": 447, "name": "Bonney Lake", "parentValueId": None},
                        {"id": 33, "name": "Boone", "parentValueId": None},
                        {"id": 34, "name": "Boston", "parentValueId": None},
                        {"id": 35, "name": "Boulder", "parentValueId": None},
                        {"id": 36, "name": "Bowdoin", "parentValueId": None},
                        {"id": 37, "name": "Bowling Green", "parentValueId": None},
                        {"id": 38, "name": "Brattleboro", "parentValueId": None},
                        {"id": 494, "name": "Brevard", "parentValueId": None},
                        {
                            "id": 495,
                            "name": "Brigham Young University - Idaho",
                            "parentValueId": None,
                        },
                        {
                            "id": 531,
                            "name": "Bright Star Secondary Charter Academy",
                            "parentValueId": None,
                        },
                        {"id": 401, "name": "Bronx", "parentValueId": None},
                        {"id": 309, "name": "Brookfield", "parentValueId": None},
                        {"id": 417, "name": "Brookings", "parentValueId": None},
                        {"id": 380, "name": "Brookline", "parentValueId": None},
                        {"id": 351, "name": "Brooklyn Artists", "parentValueId": None},
                        {"id": 39, "name": "Broward", "parentValueId": None},
                        {"id": 40, "name": "Brown and RISD", "parentValueId": None},
                        {"id": 373, "name": "Brunswick", "parentValueId": None},
                        {"id": 41, "name": "Bryn Mawr", "parentValueId": None},
                        {"id": 42, "name": "Buffalo NY", "parentValueId": None},
                        {"id": 363, "name": "Buncombe", "parentValueId": None},
                        {"id": 578, "name": "Burbank", "parentValueId": None},
                        {"id": 43, "name": "Burlington", "parentValueId": None},
                        {"id": 44, "name": "Burnt Hills", "parentValueId": None},
                        {"id": 559, "name": "Cambridge", "parentValueId": None},
                        {"id": 45, "name": "Cape Cod", "parentValueId": None},
                        {"id": 381, "name": "Carleton", "parentValueId": None},
                        {"id": 46, "name": "Carnegie Vanguard", "parentValueId": None},
                        {"id": 465, "name": "Carroll County", "parentValueId": None},
                        {"id": 352, "name": "Cary", "parentValueId": None},
                        {
                            "id": 47,
                            "name": "Case Western Reserve University",
                            "parentValueId": None,
                        },
                        {"id": 48, "name": "Cedar Rapids", "parentValueId": None},
                        {
                            "id": 553,
                            "name": "Champaign-Urbana Annapolis",
                            "parentValueId": None,
                        },
                        {
                            "id": 49,
                            "name": "Chapel Hill & Carrboro",
                            "parentValueId": None,
                        },
                        {"id": 571, "name": "Charleston", "parentValueId": None},
                        {"id": 50, "name": "Charlotte", "parentValueId": None},
                        {"id": 51, "name": "Charlottesville", "parentValueId": None},
                        {"id": 441, "name": "Chattanooga", "parentValueId": None},
                        {"id": 496, "name": "Cheltenham", "parentValueId": None},
                        {"id": 52, "name": "Chesapeake", "parentValueId": None},
                        {"id": 471, "name": "Chesterfield", "parentValueId": None},
                        {"id": 53, "name": "Chicago", "parentValueId": None},
                        {"id": 54, "name": "Chico", "parentValueId": None},
                        {"id": 539, "name": "Cincinnati", "parentValueId": None},
                        {"id": 55, "name": "Claremont Colleges", "parentValueId": None},
                        {"id": 426, "name": "Clarksburg", "parentValueId": None},
                        {"id": 56, "name": "Clayton County", "parentValueId": None},
                        {"id": 57, "name": "Clearwater", "parentValueId": None},
                        {"id": 427, "name": "Clermont", "parentValueId": None},
                        {"id": 58, "name": "Cleveland", "parentValueId": None},
                        {"id": 60, "name": "Coeur d\u2019Alene", "parentValueId": None},
                        {"id": 428, "name": "Colby", "parentValueId": None},
                        {"id": 560, "name": "Colgate", "parentValueId": None},
                        {"id": 61, "name": "Colorado Springs", "parentValueId": None},
                        {"id": 497, "name": "Columbia", "parentValueId": None},
                        {
                            "id": 63,
                            "name": "Columbia University",
                            "parentValueId": None,
                        },
                        {"id": 64, "name": "Columbus", "parentValueId": None},
                        {"id": 62, "name": "CoMo", "parentValueId": None},
                        {"id": 382, "name": "Concord Academy", "parentValueId": None},
                        {"id": 65, "name": "Concord-Carlisle", "parentValueId": None},
                        {"id": 448, "name": "Conestoga", "parentValueId": None},
                        {"id": 66, "name": "Connecticut", "parentValueId": None},
                        {"id": 498, "name": "Contra Costa", "parentValueId": None},
                        {
                            "id": 67,
                            "name": "Contra Costa County",
                            "parentValueId": None,
                        },
                        {"id": 547, "name": "Corpus Christi", "parentValueId": None},
                        {"id": 68, "name": "Corvallis", "parentValueId": None},
                        {"id": 69, "name": "Crefeld", "parentValueId": None},
                        {
                            "id": 70,
                            "name": "Culinary Institute of America",
                            "parentValueId": None,
                        },
                        {
                            "id": 449,
                            "name": "Culver City High School",
                            "parentValueId": None,
                        },
                        {"id": 71, "name": "Dallas", "parentValueId": None},
                        {"id": 72, "name": "Danbury", "parentValueId": None},
                        {"id": 327, "name": "Dartmouth", "parentValueId": None},
                        {"id": 499, "name": "Davidson College", "parentValueId": None},
                        {"id": 73, "name": "Davis", "parentValueId": None},
                        {"id": 74, "name": "Dayton", "parentValueId": None},
                        {"id": 342, "name": "DC", "parentValueId": None},
                        {"id": 472, "name": "De Anza College", "parentValueId": None},
                        {"id": 500, "name": "Dearborn", "parentValueId": None},
                        {"id": 572, "name": "DECA", "parentValueId": None},
                        {"id": 501, "name": "Decatur", "parentValueId": None},
                        {"id": 402, "name": "DeKalb", "parentValueId": None},
                        {"id": 75, "name": "Denver", "parentValueId": None},
                        {"id": 76, "name": "DePaul", "parentValueId": None},
                        {"id": 77, "name": "Des Moines", "parentValueId": None},
                        {"id": 78, "name": "Detroit", "parentValueId": None},
                        {"id": 502, "name": "Dickinson College", "parentValueId": None},
                        {"id": 364, "name": "Downtown San Jose", "parentValueId": None},
                        {"id": 450, "name": "Downtown School", "parentValueId": None},
                        {"id": 79, "name": "Drexel University", "parentValueId": None},
                        {"id": 442, "name": "Dublin", "parentValueId": None},
                        {"id": 80, "name": "Dubuque", "parentValueId": None},
                        {"id": 81, "name": "Durham", "parentValueId": None},
                        {"id": 82, "name": "East Bay", "parentValueId": None},
                        {"id": 83, "name": "Eastern Washington", "parentValueId": None},
                        {"id": 84, "name": "Easthampton", "parentValueId": None},
                        {"id": 310, "name": "Eden Prairie", "parentValueId": None},
                        {"id": 85, "name": "Edwardsville", "parentValueId": None},
                        {"id": 503, "name": "Einstein", "parentValueId": None},
                        {"id": 86, "name": "El Paso", "parentValueId": None},
                        {"id": 87, "name": "Emory", "parentValueId": None},
                        {"id": 383, "name": "Endicott College", "parentValueId": None},
                        {"id": 88, "name": "Eugene", "parentValueId": None},
                        {"id": 89, "name": "Evanston", "parentValueId": None},
                        {"id": 91, "name": "Fairfax County", "parentValueId": None},
                        {"id": 92, "name": "Fairfield CT", "parentValueId": None},
                        {
                            "id": 93,
                            "name": "Fairleigh Dickinson University",
                            "parentValueId": None,
                        },
                        {"id": 311, "name": "Fairview", "parentValueId": None},
                        {"id": 456, "name": "Fargo South", "parentValueId": None},
                        {"id": 94, "name": "Flagstaff", "parentValueId": None},
                        {"id": 504, "name": "Flat Rock", "parentValueId": None},
                        {
                            "id": 384,
                            "name": "Florida Atlantic University",
                            "parentValueId": None,
                        },
                        {
                            "id": 95,
                            "name": "Florida Golf Coast University",
                            "parentValueId": None,
                        },
                        {
                            "id": 457,
                            "name": "Fordham University",
                            "parentValueId": None,
                        },
                        {"id": 96, "name": "Fort Collins", "parentValueId": None},
                        {"id": 97, "name": "Fort Wayne", "parentValueId": None},
                        {"id": 473, "name": "Fox Chapel", "parentValueId": None},
                        {"id": 98, "name": "Franklin", "parentValueId": None},
                        {"id": 99, "name": "Franklin County", "parentValueId": None},
                        {"id": 312, "name": "Frederick", "parentValueId": None},
                        {"id": 100, "name": "Fredericksburg", "parentValueId": None},
                        {"id": 101, "name": "Fresno", "parentValueId": None},
                        {"id": 458, "name": "Frisco", "parentValueId": None},
                        {"id": 102, "name": "Gallatin Valley", "parentValueId": None},
                        {"id": 505, "name": "Garfield", "parentValueId": None},
                        {
                            "id": 506,
                            "name": "George Mason University",
                            "parentValueId": None,
                        },
                        {
                            "id": 103,
                            "name": "George Washington University",
                            "parentValueId": None,
                        },
                        {
                            "id": 104,
                            "name": "Georgetown Day School",
                            "parentValueId": None,
                        },
                        {
                            "id": 313,
                            "name": "Georgetown University",
                            "parentValueId": None,
                        },
                        {
                            "id": 105,
                            "name": "Georgia State University",
                            "parentValueId": None,
                        },
                        {"id": 532, "name": "Glendale", "parentValueId": None},
                        {
                            "id": 429,
                            "name": "Glendora High School",
                            "parentValueId": None,
                        },
                        {"id": 106, "name": "Goshen", "parentValueId": None},
                        {"id": 328, "name": "Goucher", "parentValueId": None},
                        {"id": 107, "name": "Grand Rapids", "parentValueId": None},
                        {
                            "id": 430,
                            "name": "Granite Bay High School",
                            "parentValueId": None,
                        },
                        {"id": 108, "name": "Great Neck", "parentValueId": None},
                        {"id": 397, "name": "Greater Lafayette", "parentValueId": None},
                        {
                            "id": 109,
                            "name": "Greater Morgantown",
                            "parentValueId": None,
                        },
                        {"id": 110, "name": "Greensboro", "parentValueId": None},
                        {"id": 111, "name": "Greenville", "parentValueId": None},
                        {"id": 112, "name": "Grinnell", "parentValueId": None},
                        {"id": 314, "name": "Groton", "parentValueId": None},
                        {"id": 474, "name": "Gwinnett", "parentValueId": None},
                        {"id": 113, "name": "Hamilton College", "parentValueId": None},
                        {"id": 114, "name": "Hampden County", "parentValueId": None},
                        {"id": 115, "name": "Harrisonburg", "parentValueId": None},
                        {"id": 116, "name": "Haverford", "parentValueId": None},
                        {
                            "id": 118,
                            "name": "Henry Ford College",
                            "parentValueId": None,
                        },
                        {"id": 119, "name": "Hernando County", "parentValueId": None},
                        {"id": 563, "name": "Hillsborough", "parentValueId": None},
                        {"id": 120, "name": "Hilltowns", "parentValueId": None},
                        {"id": 564, "name": "Holland", "parentValueId": None},
                        {"id": 121, "name": "Homestead", "parentValueId": None},
                        {"id": 117, "name": "Honolulu", "parentValueId": None},
                        {
                            "id": 554,
                            "name": "Hood River Valley High School",
                            "parentValueId": None,
                        },
                        {"id": 315, "name": "Hopkins", "parentValueId": None},
                        {"id": 122, "name": "Houston", "parentValueId": None},
                        {"id": 123, "name": "Howard County", "parentValueId": None},
                        {"id": 124, "name": "Humboldt County", "parentValueId": None},
                        {"id": 125, "name": "Hunterdon County", "parentValueId": None},
                        {"id": 126, "name": "Huntington", "parentValueId": None},
                        {"id": 127, "name": "Huntington Beach", "parentValueId": None},
                        {"id": 128, "name": "Huntsville", "parentValueId": None},
                        {"id": 129, "name": "Idyllwild", "parentValueId": None},
                        {"id": 130, "name": "Indianapolis", "parentValueId": None},
                        {"id": 131, "name": "Inland Empire", "parentValueId": None},
                        {"id": 90, "name": "Interior Alaska", "parentValueId": None},
                        {"id": 374, "name": "Interlochen", "parentValueId": None},
                        {
                            "id": 132,
                            "name": "International School of Los Angeles",
                            "parentValueId": None,
                        },
                        {"id": 555, "name": "Iowa City", "parentValueId": None},
                        {"id": 329, "name": "Ipswich", "parentValueId": None},
                        {"id": 133, "name": "Irvine", "parentValueId": None},
                        {"id": 561, "name": "Issaquah", "parentValueId": None},
                        {"id": 134, "name": "Ithaca", "parentValueId": None},
                        {"id": 135, "name": "Jackson Hole", "parentValueId": None},
                        {"id": 136, "name": "Jay County HS", "parentValueId": None},
                        {"id": 137, "name": "Jenkintown", "parentValueId": None},
                        {"id": 138, "name": "Jersey Shore", "parentValueId": None},
                        {
                            "id": 431,
                            "name": "John Burroughs School",
                            "parentValueId": None,
                        },
                        {"id": 332, "name": "Joliet", "parentValueId": None},
                        {
                            "id": 459,
                            "name": "Jones College Prep",
                            "parentValueId": None,
                        },
                        {"id": 432, "name": "Jordan", "parentValueId": None},
                        {"id": 418, "name": "Justin-Siena", "parentValueId": None},
                        {"id": 139, "name": "Kalamazoo", "parentValueId": None},
                        {"id": 140, "name": "Kansas City", "parentValueId": None},
                        {"id": 408, "name": "Katy", "parentValueId": None},
                        {"id": 433, "name": "Kent State", "parentValueId": None},
                        {"id": 507, "name": "Kenyon", "parentValueId": None},
                        {"id": 353, "name": "Kern", "parentValueId": None},
                        {"id": 475, "name": "Kern Youth", "parentValueId": None},
                        {"id": 141, "name": "Kirksville", "parentValueId": None},
                        {"id": 142, "name": "Knoxville", "parentValueId": None},
                        {"id": 143, "name": "Kodiak", "parentValueId": None},
                        {"id": 460, "name": "La Crescenta", "parentValueId": None},
                        {"id": 476, "name": "Ladue", "parentValueId": None},
                        {"id": 354, "name": "Lafayette", "parentValueId": None},
                        {"id": 548, "name": "Lake/Sumter", "parentValueId": None},
                        {"id": 144, "name": "Lambertville", "parentValueId": None},
                        {
                            "id": 145,
                            "name": "Lancaster High School",
                            "parentValueId": None,
                        },
                        {"id": 146, "name": "Lansing", "parentValueId": None},
                        {"id": 355, "name": "Laramie", "parentValueId": None},
                        {"id": 147, "name": "Lawrence", "parentValueId": None},
                        {"id": 508, "name": "Lee's Summit", "parentValueId": None},
                        {"id": 347, "name": "Lehigh", "parentValueId": None},
                        {"id": 148, "name": "Lehigh Valley", "parentValueId": None},
                        {
                            "id": 149,
                            "name": "Lehman Alternative Community School",
                            "parentValueId": None,
                        },
                        {"id": 150, "name": "Lewisburg", "parentValueId": None},
                        {
                            "id": 533,
                            "name": "Lewisburg Area High School",
                            "parentValueId": None,
                        },
                        {"id": 348, "name": "Lexington KY", "parentValueId": None},
                        {"id": 151, "name": "Lexington MA", "parentValueId": None},
                        {"id": 403, "name": "Litchfield", "parentValueId": None},
                        {"id": 152, "name": "Little Rock", "parentValueId": None},
                        {"id": 534, "name": "Livingston", "parentValueId": None},
                        {"id": 395, "name": "Long Beach", "parentValueId": None},
                        {"id": 153, "name": "Long Island", "parentValueId": None},
                        {"id": 154, "name": "Los Angeles", "parentValueId": None},
                        {"id": 372, "name": "Los Angeles Youth", "parentValueId": None},
                        {
                            "id": 509,
                            "name": "Los Osos High School",
                            "parentValueId": None,
                        },
                        {"id": 510, "name": "Loudoun", "parentValueId": None},
                        {"id": 155, "name": "Louisville", "parentValueId": None},
                        {"id": 477, "name": "Louisville Youth", "parentValueId": None},
                        {"id": 478, "name": "Loveland", "parentValueId": None},
                        {
                            "id": 330,
                            "name": "Lowell High School",
                            "parentValueId": None,
                        },
                        {
                            "id": 316,
                            "name": "Loyola University Chicago",
                            "parentValueId": None,
                        },
                        {"id": 317, "name": "Lyc\u00e9e", "parentValueId": None},
                        {"id": 434, "name": "Lynn", "parentValueId": None},
                        {"id": 156, "name": "Madison", "parentValueId": None},
                        {
                            "id": 157,
                            "name": "Manchester University",
                            "parentValueId": None,
                        },
                        {"id": 158, "name": "Manhattan", "parentValueId": None},
                        {"id": 159, "name": "Mankato", "parentValueId": None},
                        {"id": 160, "name": "Maple Grove", "parentValueId": None},
                        {"id": 356, "name": "Marblehead", "parentValueId": None},
                        {"id": 161, "name": "Marin", "parentValueId": None},
                        {"id": 162, "name": "Martha's Vineyard", "parentValueId": None},
                        {
                            "id": 535,
                            "name": "Martha's Vineyard Youth",
                            "parentValueId": None,
                        },
                        {"id": 479, "name": "McDaniel", "parentValueId": None},
                        {"id": 480, "name": "McFarland", "parentValueId": None},
                        {"id": 517, "name": "McGill", "parentValueId": None},
                        {"id": 365, "name": "McLean", "parentValueId": None},
                        {"id": 466, "name": "Memorial", "parentValueId": None},
                        {"id": 163, "name": "MetroWest", "parentValueId": None},
                        {"id": 343, "name": "Miami", "parentValueId": None},
                        {"id": 385, "name": "Miami University", "parentValueId": None},
                        {"id": 164, "name": "Middlebury", "parentValueId": None},
                        {"id": 549, "name": "Middlesex County", "parentValueId": None},
                        {"id": 165, "name": "Middletown", "parentValueId": None},
                        {
                            "id": 333,
                            "name": "Milford High School",
                            "parentValueId": None,
                        },
                        {"id": 573, "name": "Millburn", "parentValueId": None},
                        {"id": 166, "name": "Mills College", "parentValueId": None},
                        {"id": 167, "name": "Milwaukee", "parentValueId": None},
                        {"id": 344, "name": "Minneapolis", "parentValueId": None},
                        {"id": 366, "name": "Mission", "parentValueId": None},
                        {"id": 168, "name": "Mississippi", "parentValueId": None},
                        {
                            "id": 511,
                            "name": "Mississippi Gulf Coast",
                            "parentValueId": None,
                        },
                        {"id": 169, "name": "Missoula", "parentValueId": None},
                        {"id": 170, "name": "Montclair", "parentValueId": None},
                        {"id": 550, "name": "Montco", "parentValueId": None},
                        {"id": 461, "name": "Monterey", "parentValueId": None},
                        {"id": 171, "name": "Montpelier", "parentValueId": None},
                        {"id": 551, "name": "Mooresville", "parentValueId": None},
                        {"id": 172, "name": "Morris County", "parentValueId": None},
                        {"id": 174, "name": "Mountain View HS", "parentValueId": None},
                        {"id": 175, "name": "Muhlenberg", "parentValueId": None},
                        {"id": 349, "name": "Murray", "parentValueId": None},
                        {"id": 176, "name": "Nashville", "parentValueId": None},
                        {"id": 536, "name": "Nassau", "parentValueId": None},
                        {
                            "id": 451,
                            "name": "Nathan Hale High School",
                            "parentValueId": None,
                        },
                        {
                            "id": 452,
                            "name": "Natick High School",
                            "parentValueId": None,
                        },
                        {
                            "id": 386,
                            "name": "Naugatuck High School",
                            "parentValueId": None,
                        },
                        {"id": 177, "name": "Nevada County", "parentValueId": None},
                        {"id": 178, "name": "New Canaan", "parentValueId": None},
                        {
                            "id": 179,
                            "name": "New College of Florida",
                            "parentValueId": None,
                        },
                        {
                            "id": 318,
                            "name": "New England Academy",
                            "parentValueId": None,
                        },
                        {"id": 180, "name": "New Hampshire", "parentValueId": None},
                        {"id": 181, "name": "New Haven", "parentValueId": None},
                        {"id": 182, "name": "New Orleans", "parentValueId": None},
                        {
                            "id": 396,
                            "name": "New Trier Township",
                            "parentValueId": None,
                        },
                        {"id": 183, "name": "New York City", "parentValueId": None},
                        {
                            "id": 184,
                            "name": "New York University",
                            "parentValueId": None,
                        },
                        {"id": 285, "name": "Newark", "parentValueId": None},
                        {"id": 319, "name": "Newburyport", "parentValueId": None},
                        {"id": 435, "name": "Niwot", "parentValueId": None},
                        {"id": 185, "name": "NJ Skylands", "parentValueId": None},
                        {"id": 186, "name": "Norfolk", "parentValueId": None},
                        {"id": 405, "name": "Normal", "parentValueId": None},
                        {"id": 187, "name": "North Dakota", "parentValueId": None},
                        {"id": 188, "name": "North Georgia", "parentValueId": None},
                        {"id": 481, "name": "North Hollywood", "parentValueId": None},
                        {
                            "id": 414,
                            "name": "North Shore Chicago",
                            "parentValueId": None,
                        },
                        {"id": 189, "name": "Northampton", "parentValueId": None},
                        {
                            "id": 190,
                            "name": "Northeastern University",
                            "parentValueId": None,
                        },
                        {"id": 540, "name": "Northern Kentucky", "parentValueId": None},
                        {
                            "id": 387,
                            "name": "Northern New Mexico",
                            "parentValueId": None,
                        },
                        {"id": 357, "name": "Northwest", "parentValueId": None},
                        {
                            "id": 191,
                            "name": "Northwest Philadelphia",
                            "parentValueId": None,
                        },
                        {
                            "id": 192,
                            "name": "Northwest-Southwest Suburbs",
                            "parentValueId": None,
                        },
                        {"id": 193, "name": "Norton", "parentValueId": None},
                        {"id": 440, "name": "Not in a hub", "parentValueId": None},
                        {"id": 482, "name": "NYC Youth", "parentValueId": None},
                        {"id": 469, "name": "NYU", "parentValueId": None},
                        {
                            "id": 545,
                            "name": "Oak Park and River Forest High School",
                            "parentValueId": None,
                        },
                        {"id": 194, "name": "Oakland County", "parentValueId": None},
                        {"id": 195, "name": "Oberlin", "parentValueId": None},
                        {"id": 462, "name": "Ocala", "parentValueId": None},
                        {"id": 512, "name": "Occidental", "parentValueId": None},
                        {"id": 196, "name": "Ogden", "parentValueId": None},
                        {"id": 197, "name": "Oklahoma City", "parentValueId": None},
                        {
                            "id": 513,
                            "name": "Oklahoma City University",
                            "parentValueId": None,
                        },
                        {"id": 198, "name": "Olympia", "parentValueId": None},
                        {"id": 199, "name": "Omaha", "parentValueId": None},
                        {"id": 566, "name": "Oneonta", "parentValueId": None},
                        {"id": 320, "name": "Open Connections", "parentValueId": None},
                        {"id": 200, "name": "Orange County", "parentValueId": None},
                        {"id": 201, "name": "Orlando", "parentValueId": None},
                        {
                            "id": 406,
                            "name": "Ottawa Hills High School",
                            "parentValueId": None,
                        },
                        {"id": 453, "name": "Owen", "parentValueId": None},
                        {"id": 202, "name": "Palm Beach County", "parentValueId": None},
                        {"id": 203, "name": "Palo Alto", "parentValueId": None},
                        {"id": 436, "name": "Park Ridge", "parentValueId": None},
                        {"id": 514, "name": "Payton", "parentValueId": None},
                        {"id": 484, "name": "Penn Alexander", "parentValueId": None},
                        {
                            "id": 515,
                            "name": "Penn State Harrisburg",
                            "parentValueId": None,
                        },
                        {
                            "id": 204,
                            "name": "Pennsbury High School",
                            "parentValueId": None,
                        },
                        {"id": 205, "name": "Philadelphia", "parentValueId": None},
                        {"id": 516, "name": "Phillips", "parentValueId": None},
                        {
                            "id": 375,
                            "name": "Phillips Exeter Academy",
                            "parentValueId": None,
                        },
                        {"id": 206, "name": "Phoenix", "parentValueId": None},
                        {
                            "id": 493,
                            "name": "Pioneer Valley Chinese Immersion Charter School",
                            "parentValueId": None,
                        },
                        {"id": 207, "name": "Pittsburgh", "parentValueId": None},
                        {"id": 208, "name": "Placer County", "parentValueId": None},
                        {"id": 367, "name": "Plainview", "parentValueId": None},
                        {"id": 485, "name": "Plant High School", "parentValueId": None},
                        {"id": 544, "name": "Plattsburgh", "parentValueId": None},
                        {
                            "id": 556,
                            "name": "Point Pleasant Beach",
                            "parentValueId": None,
                        },
                        {
                            "id": 321,
                            "name": "Pope Francis Preparatory School",
                            "parentValueId": None,
                        },
                        {"id": 209, "name": "Portland ME", "parentValueId": None},
                        {"id": 210, "name": "Portland OR", "parentValueId": None},
                        {"id": 337, "name": "Poughkeepsie", "parentValueId": None},
                        {
                            "id": 211,
                            "name": "Prince George's County",
                            "parentValueId": None,
                        },
                        {"id": 212, "name": "Princeton", "parentValueId": None},
                        {"id": 213, "name": "Providence", "parentValueId": None},
                        {
                            "id": 322,
                            "name": "Providence Area High Schools",
                            "parentValueId": None,
                        },
                        {"id": 214, "name": "Puerto Rico", "parentValueId": None},
                        {"id": 215, "name": "Raleigh", "parentValueId": None},
                        {"id": 216, "name": "Rancho Cucamonga", "parentValueId": None},
                        {"id": 407, "name": "Red Hook", "parentValueId": None},
                        {"id": 443, "name": "Redding", "parentValueId": None},
                        {"id": 217, "name": "Redondo Beach", "parentValueId": None},
                        {"id": 419, "name": "Reed", "parentValueId": None},
                        {"id": 388, "name": "Reno", "parentValueId": None},
                        {"id": 218, "name": "RGV", "parentValueId": None},
                        {
                            "id": 486,
                            "name": "Rhode Island Youth",
                            "parentValueId": None,
                        },
                        {"id": 518, "name": "Rhodes", "parentValueId": None},
                        {
                            "id": 519,
                            "name": "Richard Montgomery",
                            "parentValueId": None,
                        },
                        {"id": 219, "name": "Richmond", "parentValueId": None},
                        {"id": 520, "name": "Ridgewood", "parentValueId": None},
                        {"id": 220, "name": "Rivertowns NY", "parentValueId": None},
                        {"id": 221, "name": "Roanoke", "parentValueId": None},
                        {"id": 537, "name": "Rochester MN", "parentValueId": None},
                        {"id": 222, "name": "Rochester NY", "parentValueId": None},
                        {
                            "id": 223,
                            "name": "Rockingham-Hillsborough",
                            "parentValueId": None,
                        },
                        {"id": 487, "name": "Rockland", "parentValueId": None},
                        {"id": 404, "name": "Rockville", "parentValueId": None},
                        {"id": 224, "name": "Rockville Centre", "parentValueId": None},
                        {"id": 225, "name": "Rolla", "parentValueId": None},
                        {"id": 546, "name": "Roosevelt", "parentValueId": None},
                        {"id": 541, "name": "Roslyn", "parentValueId": None},
                        {"id": 521, "name": "Roswell", "parentValueId": None},
                        {
                            "id": 226,
                            "name": "Rutgers University",
                            "parentValueId": None,
                        },
                        {"id": 227, "name": "Sacramento", "parentValueId": None},
                        {"id": 228, "name": "Salem", "parentValueId": None},
                        {"id": 229, "name": "Salinas", "parentValueId": None},
                        {"id": 230, "name": "Salt Lake City", "parentValueId": None},
                        {"id": 231, "name": "San Antonio", "parentValueId": None},
                        {"id": 232, "name": "San Diego", "parentValueId": None},
                        {"id": 488, "name": "San Diego Youth", "parentValueId": None},
                        {
                            "id": 437,
                            "name": "San Francisco University High School",
                            "parentValueId": None,
                        },
                        {"id": 323, "name": "San Jose", "parentValueId": None},
                        {"id": 248, "name": "San Luis Obispo", "parentValueId": None},
                        {"id": 233, "name": "San Ramon", "parentValueId": None},
                        {"id": 234, "name": "Santa Barbara", "parentValueId": None},
                        {"id": 522, "name": "Santa Clara", "parentValueId": None},
                        {
                            "id": 235,
                            "name": "Santa Clara University",
                            "parentValueId": None,
                        },
                        {"id": 236, "name": "Santa Cruz", "parentValueId": None},
                        {"id": 237, "name": "Santa Fe", "parentValueId": None},
                        {"id": 238, "name": "Santa Ynez", "parentValueId": None},
                        {"id": 239, "name": "Sarah Lawrence", "parentValueId": None},
                        {"id": 240, "name": "Scattergood", "parentValueId": None},
                        {
                            "id": 489,
                            "name": "School of the Arts",
                            "parentValueId": None,
                        },
                        {"id": 241, "name": "Scioto", "parentValueId": None},
                        {"id": 242, "name": "Scottsdale", "parentValueId": None},
                        {"id": 243, "name": "Seattle", "parentValueId": None},
                        {
                            "id": 368,
                            "name": "Seattle Girls' School",
                            "parentValueId": None,
                        },
                        {"id": 345, "name": "Sebastopol Youth", "parentValueId": None},
                        {"id": 490, "name": "Shawnee", "parentValueId": None},
                        {"id": 245, "name": "Shoreham", "parentValueId": None},
                        {"id": 422, "name": "Shreveport", "parentValueId": None},
                        {"id": 389, "name": "Silicon Valley", "parentValueId": None},
                        {"id": 246, "name": "Silver Spring", "parentValueId": None},
                        {"id": 247, "name": "Simon\u2019s Rock", "parentValueId": None},
                        {"id": 390, "name": "Siskiyou", "parentValueId": None},
                        {"id": 391, "name": "Smith College", "parentValueId": None},
                        {"id": 59, "name": "SoCal Desert", "parentValueId": None},
                        {"id": 491, "name": "Solano County", "parentValueId": None},
                        {"id": 358, "name": "Somerset Berkley", "parentValueId": None},
                        {"id": 523, "name": "Somerville Youth", "parentValueId": None},
                        {"id": 249, "name": "Sonoma County", "parentValueId": None},
                        {"id": 250, "name": "South Bend", "parentValueId": None},
                        {"id": 252, "name": "South County", "parentValueId": None},
                        {"id": 253, "name": "South Florida", "parentValueId": None},
                        {"id": 341, "name": "South Hadley", "parentValueId": None},
                        {"id": 254, "name": "South Jersey", "parentValueId": None},
                        {"id": 438, "name": "South Kitsap", "parentValueId": None},
                        {"id": 255, "name": "South Lake Tahoe", "parentValueId": None},
                        {"id": 369, "name": "South Philly", "parentValueId": None},
                        {"id": 256, "name": "South Shore", "parentValueId": None},
                        {"id": 392, "name": "South Windsor", "parentValueId": None},
                        {"id": 251, "name": "Southcoast", "parentValueId": None},
                        {"id": 257, "name": "Southern Illinois", "parentValueId": None},
                        {"id": 415, "name": "Southside Chicago", "parentValueId": None},
                        {"id": 339, "name": "Spokane", "parentValueId": None},
                        {"id": 258, "name": "Springfield MO", "parentValueId": None},
                        {
                            "id": 259,
                            "name": "Springside Chestnut Hill Academy",
                            "parentValueId": None,
                        },
                        {
                            "id": 260,
                            "name": "St. Lawrence University",
                            "parentValueId": None,
                        },
                        {"id": 261, "name": "St. Louis", "parentValueId": None},
                        {"id": 262, "name": "St. Olaf", "parentValueId": None},
                        {"id": 279, "name": "St. Paul", "parentValueId": None},
                        {
                            "id": 263,
                            "name": "Stanford University",
                            "parentValueId": None,
                        },
                        {"id": 264, "name": "State College", "parentValueId": None},
                        {"id": 265, "name": "Steinbrenner", "parentValueId": None},
                        {
                            "id": 409,
                            "name": "Stockton University",
                            "parentValueId": None,
                        },
                        {"id": 266, "name": "Stonington", "parentValueId": None},
                        {
                            "id": 267,
                            "name": "Stony Brook University",
                            "parentValueId": None,
                        },
                        {"id": 268, "name": "Susitna", "parentValueId": None},
                        {"id": 269, "name": "Swarthmore", "parentValueId": None},
                        {"id": 492, "name": "Syosset", "parentValueId": None},
                        {"id": 270, "name": "Syracus", "parentValueId": None},
                        {"id": 552, "name": "Syracuse", "parentValueId": None},
                        {"id": 271, "name": "Tacoma", "parentValueId": None},
                        {"id": 272, "name": "Tallahassee", "parentValueId": None},
                        {"id": 393, "name": "Tampa", "parentValueId": None},
                        {"id": 376, "name": "Tempe", "parentValueId": None},
                        {"id": 273, "name": "Temple University", "parentValueId": None},
                        {"id": 398, "name": "Thousand Oaks", "parentValueId": None},
                        {"id": 557, "name": "Tidewater", "parentValueId": None},
                        {"id": 562, "name": "Toe Valley", "parentValueId": None},
                        {"id": 275, "name": "Towson", "parentValueId": None},
                        {"id": 276, "name": "Traverse City", "parentValueId": None},
                        {"id": 574, "name": "Trischools", "parentValueId": None},
                        {"id": 524, "name": "Troy", "parentValueId": None},
                        {"id": 277, "name": "Tucson", "parentValueId": None},
                        {"id": 278, "name": "Tufts University", "parentValueId": None},
                        {"id": 525, "name": "Tulane", "parentValueId": None},
                        {"id": 420, "name": "Tulsa", "parentValueId": None},
                        {"id": 394, "name": "UC San Diego", "parentValueId": None},
                        {"id": 280, "name": "UMass Amherst", "parentValueId": None},
                        {"id": 350, "name": "UMass Boston", "parentValueId": None},
                        {"id": 526, "name": "UNC Asheville", "parentValueId": None},
                        {"id": 370, "name": "Union County", "parentValueId": None},
                        {"id": 281, "name": "Unity", "parentValueId": None},
                        {
                            "id": 282,
                            "name": "University of Arkansas Fayetteville",
                            "parentValueId": None,
                        },
                        {
                            "id": 542,
                            "name": "University of California Berkeley",
                            "parentValueId": None,
                        },
                        {
                            "id": 283,
                            "name": "University of California Irvine",
                            "parentValueId": None,
                        },
                        {
                            "id": 284,
                            "name": "University of Connecticut",
                            "parentValueId": None,
                        },
                        {
                            "id": 567,
                            "name": "University of Georgia",
                            "parentValueId": None,
                        },
                        {
                            "id": 410,
                            "name": "University of Houston",
                            "parentValueId": None,
                        },
                        {
                            "id": 467,
                            "name": "University of Maine",
                            "parentValueId": None,
                        },
                        {
                            "id": 421,
                            "name": "University of Maryland",
                            "parentValueId": None,
                        },
                        {
                            "id": 463,
                            "name": "University of North Carolina School of the Arts",
                            "parentValueId": None,
                        },
                        {
                            "id": 286,
                            "name": "University of Oklahoma",
                            "parentValueId": None,
                        },
                        {
                            "id": 324,
                            "name": "University of San Diego",
                            "parentValueId": None,
                        },
                        {
                            "id": 287,
                            "name": "University of South Carolina",
                            "parentValueId": None,
                        },
                        {
                            "id": 288,
                            "name": "University of Utah",
                            "parentValueId": None,
                        },
                        {
                            "id": 527,
                            "name": "University of Washington",
                            "parentValueId": None,
                        },
                        {"id": 543, "name": "Upstate SC", "parentValueId": None},
                        {"id": 289, "name": "Vancouver", "parentValueId": None},
                        {"id": 454, "name": "Vanderbilt", "parentValueId": None},
                        {"id": 291, "name": "Vegas", "parentValueId": None},
                        {"id": 292, "name": "Venice", "parentValueId": None},
                        {"id": 538, "name": "Vermillion", "parentValueId": None},
                        {"id": 331, "name": "Villanova", "parentValueId": None},
                        {"id": 411, "name": "Visitation", "parentValueId": None},
                        {"id": 530, "name": "Wachusett", "parentValueId": None},
                        {"id": 293, "name": "Wakefield", "parentValueId": None},
                        {"id": 325, "name": "Wakeland", "parentValueId": None},
                        {"id": 294, "name": "Walla Walla", "parentValueId": None},
                        {
                            "id": 334,
                            "name": "Walla Walla University",
                            "parentValueId": None,
                        },
                        {
                            "id": 295,
                            "name": "Wallingford-Swarthmore",
                            "parentValueId": None,
                        },
                        {"id": 296, "name": "Waltham", "parentValueId": None},
                        {"id": 568, "name": "Warren County", "parentValueId": None},
                        {
                            "id": 298,
                            "name": "Washington Heights",
                            "parentValueId": None,
                        },
                        {"id": 439, "name": "Washington State", "parentValueId": None},
                        {
                            "id": 579,
                            "name": "Washington-Liberty High School",
                            "parentValueId": None,
                        },
                        {"id": 455, "name": "Watertown", "parentValueId": None},
                        {"id": 416, "name": "Wauwatosa", "parentValueId": None},
                        {"id": 412, "name": "Waverly", "parentValueId": None},
                        {"id": 413, "name": "Waycross", "parentValueId": None},
                        {"id": 326, "name": "Wellesley", "parentValueId": None},
                        {"id": 359, "name": "West Chester PA", "parentValueId": None},
                        {"id": 528, "name": "West Marin", "parentValueId": None},
                        {"id": 444, "name": "West Seattle", "parentValueId": None},
                        {"id": 299, "name": "West Valley", "parentValueId": None},
                        {"id": 371, "name": "Westborough", "parentValueId": None},
                        {"id": 300, "name": "Westchester NY", "parentValueId": None},
                        {"id": 565, "name": "Western Mass", "parentValueId": None},
                        {
                            "id": 558,
                            "name": "Western New England University",
                            "parentValueId": None,
                        },
                        {"id": 301, "name": "Westford", "parentValueId": None},
                        {"id": 302, "name": "Westhampton Beach", "parentValueId": None},
                        {"id": 468, "name": "Whitney Young", "parentValueId": None},
                        {"id": 529, "name": "Wichita", "parentValueId": None},
                        {"id": 303, "name": "Williamsburg", "parentValueId": None},
                        {"id": 576, "name": "Williamsport", "parentValueId": None},
                        {"id": 304, "name": "Wilmington", "parentValueId": None},
                        {"id": 377, "name": "Woodbridge", "parentValueId": None},
                        {"id": 305, "name": "Worcester", "parentValueId": None},
                        {
                            "id": 577,
                            "name": "Worcester Polytechnic Institute",
                            "parentValueId": None,
                        },
                        {"id": 306, "name": "Youngstown", "parentValueId": None},
                    ],
                    "isExportable": True,
                },
                "customFieldId": 12,
                "customFieldGroupId": 4,
                "assignedValue": "176",
            },
            {
                "customField": {
                    "customFieldId": 7,
                    "customFieldParentId": None,
                    "customFieldName": "Primary Hub Role",
                    "customFieldGroupId": 4,
                    "customFieldGroupName": "Hub Role Information",
                    "customFieldGroupType": "Contacts",
                    "customFieldTypeId": "S",
                    "isEditable": True,
                    "maxTextboxCharacters": None,
                    "availableValues": [
                        {"id": 1, "name": "Action Lead", "parentValueId": None},
                        {"id": 2, "name": "Art Action Lead", "parentValueId": None},
                        {
                            "id": 22,
                            "name": "Communications Lead",
                            "parentValueId": None,
                        },
                        {"id": 3, "name": "Data Lead", "parentValueId": None},
                        {"id": 4, "name": "Electoral Lead", "parentValueId": None},
                        {
                            "id": 5,
                            "name": "Fundraising + Finance Lead",
                            "parentValueId": None,
                        },
                        {"id": 23, "name": "General member", "parentValueId": None},
                        {"id": 6, "name": "Graphic Design Lead", "parentValueId": None},
                        {"id": 7, "name": "Hub Coordinator", "parentValueId": None},
                        {"id": 8, "name": "Hub Delegate", "parentValueId": None},
                        {"id": 9, "name": "JEAO Coordinator", "parentValueId": None},
                        {
                            "id": 21,
                            "name": "Other (define in field below)",
                            "parentValueId": None,
                        },
                        {"id": 10, "name": "Partnerships Lead", "parentValueId": None},
                        {"id": 11, "name": "Photography Lead", "parentValueId": None},
                        {"id": 13, "name": "Political Lead", "parentValueId": None},
                        {"id": 14, "name": "Press + Media Lead", "parentValueId": None},
                        {"id": 15, "name": "Recruitment Lead", "parentValueId": None},
                        {"id": 16, "name": "Social Media Lead", "parentValueId": None},
                        {"id": 17, "name": "Spokesperson", "parentValueId": None},
                        {"id": 18, "name": "Team Lead", "parentValueId": None},
                        {"id": 19, "name": "Trainings Lead", "parentValueId": None},
                        {"id": 20, "name": "Video Lead", "parentValueId": None},
                    ],
                    "isExportable": True,
                },
                "customFieldId": 7,
                "customFieldGroupId": 4,
                "assignedValue": "7",
            },
            {
                "customField": {
                    "customFieldId": 8,
                    "customFieldParentId": None,
                    "customFieldName": "Secondary Hub Role",
                    "customFieldGroupId": 4,
                    "customFieldGroupName": "Hub Role Information",
                    "customFieldGroupType": "Contacts",
                    "customFieldTypeId": "S",
                    "isEditable": True,
                    "maxTextboxCharacters": None,
                    "availableValues": [
                        {"id": 1, "name": "Action Lead", "parentValueId": None},
                        {"id": 2, "name": "Art Action Lead", "parentValueId": None},
                        {
                            "id": 23,
                            "name": "Communications Lead",
                            "parentValueId": None,
                        },
                        {"id": 3, "name": "Data Lead", "parentValueId": None},
                        {"id": 4, "name": "Electoral Lead", "parentValueId": None},
                        {
                            "id": 5,
                            "name": "Fundraising + Finance Lead",
                            "parentValueId": None,
                        },
                        {"id": 22, "name": "General member", "parentValueId": None},
                        {"id": 6, "name": "Graphic Design Lead", "parentValueId": None},
                        {"id": 7, "name": "Hub Coordinator", "parentValueId": None},
                        {"id": 8, "name": "Hub Delegate", "parentValueId": None},
                        {"id": 9, "name": "JEAO Coordinator", "parentValueId": None},
                        {
                            "id": 10,
                            "name": "Other (define in field below)",
                            "parentValueId": None,
                        },
                        {"id": 11, "name": "Partnerships Lead", "parentValueId": None},
                        {"id": 12, "name": "Photography Lead", "parentValueId": None},
                        {"id": 14, "name": "Political Lead", "parentValueId": None},
                        {"id": 15, "name": "Press + Media Lead", "parentValueId": None},
                        {"id": 16, "name": "Recruitment Lead", "parentValueId": None},
                        {"id": 17, "name": "Social Media Lead", "parentValueId": None},
                        {"id": 18, "name": "Spokesperson", "parentValueId": None},
                        {"id": 19, "name": "Team Lead", "parentValueId": None},
                        {"id": 20, "name": "Trainings Lead", "parentValueId": None},
                        {"id": 21, "name": "Video Lead", "parentValueId": None},
                    ],
                    "isExportable": True,
                },
                "customFieldId": 8,
                "customFieldGroupId": 4,
                "assignedValue": None,
            },
            {
                "customField": {
                    "customFieldId": 6,
                    "customFieldParentId": None,
                    "customFieldName": "Inactive?",
                    "customFieldGroupId": 4,
                    "customFieldGroupName": "Hub Role Information",
                    "customFieldGroupType": "Contacts",
                    "customFieldTypeId": "B",
                    "isEditable": True,
                    "maxTextboxCharacters": None,
                    "availableValues": None,
                    "isExportable": True,
                },
                "customFieldId": 6,
                "customFieldGroupId": 4,
                "assignedValue": "false",
            },
            {
                "customField": {
                    "customFieldId": 9,
                    "customFieldParentId": None,
                    "customFieldName": "Other Hub Role",
                    "customFieldGroupId": 4,
                    "customFieldGroupName": "Hub Role Information",
                    "customFieldGroupType": "Contacts",
                    "customFieldTypeId": "T",
                    "isEditable": True,
                    "maxTextboxCharacters": 75,
                    "availableValues": None,
                    "isExportable": True,
                },
                "customFieldId": 9,
                "customFieldGroupId": 4,
                "assignedValue": None,
            },
        ],
    }

    expected_output = {
        "vanid": 101572625,
        "dob": "1990-08-02T00:00:00Z",
        "race": "Caucasian/White",
        "gender": "Cisgender Man,Male,Man",
        "class": "Upper/owning-class",
        "hub": "Nashville",
        "hub_role": "Hub Coordinator",
        "secondary_hub_role": None,
        "active": "false",
        "date_updated": date.today().strftime("%m/%d/%Y"),
        "other_hub_role": None,
    }

    assert (
        get_extra_fields.transform_person_for_redshift(input) == expected_output
    )


def test_extract_custom_field_values():
    input = [
        {
            "customField": {
                "customFieldId": 19,
                "customFieldParentId": None,
                "customFieldName": "Class/Economic Background",
                "customFieldGroupId": 3,
                "customFieldGroupName": "Misc. Information",
                "customFieldGroupType": "Contacts",
                "customFieldTypeId": "S",
                "isEditable": True,
                "maxTextboxCharacters": None,
                "availableValues": [
                    {"id": 1, "name": "Middle-class", "parentValueId": None},
                    {"id": 2, "name": "Poor and working-poor", "parentValueId": None},
                    {
                        "id": 3,
                        "name": "Professional/managerial-class",
                        "parentValueId": None,
                    },
                    {"id": 4, "name": "Upper/owning-class", "parentValueId": None},
                    {"id": 5, "name": "Working-class", "parentValueId": None},
                ],
                "isExportable": True,
            },
            "customFieldId": 19,
            "customFieldGroupId": 3,
            "assignedValue": "4",
        }
    ]
    output = "Upper/owning-class"
    assert get_extra_fields.extract_custom_field_values(input, 19) == output

    input = [
        {
            "customField": {
                "customFieldId": 8,
                "customFieldParentId": None,
                "customFieldName": "Secondary Hub Role",
                "customFieldGroupId": 4,
                "customFieldGroupName": "Hub Role Information",
                "customFieldGroupType": "Contacts",
                "customFieldTypeId": "S",
                "isEditable": True,
                "maxTextboxCharacters": None,
                "availableValues": [
                    {"id": 1, "name": "Action Lead", "parentValueId": None},
                    {"id": 2, "name": "Art Action Lead", "parentValueId": None},
                    {
                        "id": 23,
                        "name": "Communications Lead",
                        "parentValueId": None,
                    },
                    {"id": 3, "name": "Data Lead", "parentValueId": None},
                    {"id": 4, "name": "Electoral Lead", "parentValueId": None},
                    {
                        "id": 5,
                        "name": "Fundraising + Finance Lead",
                        "parentValueId": None,
                    },
                    {"id": 22, "name": "General member", "parentValueId": None},
                    {"id": 6, "name": "Graphic Design Lead", "parentValueId": None},
                    {"id": 7, "name": "Hub Coordinator", "parentValueId": None},
                    {"id": 8, "name": "Hub Delegate", "parentValueId": None},
                    {"id": 9, "name": "JEAO Coordinator", "parentValueId": None},
                    {
                        "id": 10,
                        "name": "Other (define in field below)",
                        "parentValueId": None,
                    },
                    {"id": 11, "name": "Partnerships Lead", "parentValueId": None},
                    {"id": 12, "name": "Photography Lead", "parentValueId": None},
                    {"id": 14, "name": "Political Lead", "parentValueId": None},
                    {"id": 15, "name": "Press + Media Lead", "parentValueId": None},
                    {"id": 16, "name": "Recruitment Lead", "parentValueId": None},
                    {"id": 17, "name": "Social Media Lead", "parentValueId": None},
                    {"id": 18, "name": "Spokesperson", "parentValueId": None},
                    {"id": 19, "name": "Team Lead", "parentValueId": None},
                    {"id": 20, "name": "Trainings Lead", "parentValueId": None},
                    {"id": 21, "name": "Video Lead", "parentValueId": None},
                ],
                "isExportable": True,
            },
            "customFieldId": 8,
            "customFieldGroupId": 4,
            "assignedValue": None,
        }
    ]
    output = None

    assert get_extra_fields.extract_custom_field_values(input, 8) == output


def test_relabel_race():
    assert get_extra_fields.relabel_race("Asian") == "Asian/Asian American"
    assert (
        get_extra_fields.relabel_race("Black or African American")
        == "Black/African American"
    )
    # TODO: finish these tests off. Also consider whether there's a more efficient testing pattern ;)